<?php

namespace App\Swagger\schemas;

use OpenApi\Attributes as OA;

#[OA\Schema(
    schema: "Summit",
    type: "object",
    properties: [
        new OA\Property(property: "id", type: "integer"),
        new OA\Property(property: "created", type: "integer"),
        new OA\Property(property: "last_edited", type: "integer"),
        new OA\Property(property: "name", type: "string"),
        new OA\Property(property: "slug", type: "string"),
        new OA\Property(property: "start_date", type: "integer", description: "Unix timestamp"),
        new OA\Property(property: "end_date", type: "integer", description: "Unix timestamp"),
        new OA\Property(property: "registration_begin_date", type: "integer", description: "Unix timestamp"),
        new OA\Property(property: "registration_end_date", type: "integer", description: "Unix timestamp"),
        new OA\Property(property: "start_showing_venues_date", type: "integer", description: "Unix timestamp"),
        new OA\Property(property: "schedule_start_date", type: "integer", description: "Unix timestamp"),
        new OA\Property(property: "active", type: "boolean"),
        new OA\Property(property: "type_id", type: "integer"),
        new OA\Property(property: "dates_label", type: "string"),
        new OA\Property(property: "max_submission_allowed_per_user", type: "integer"),
        new OA\Property(property: "published_events_count", type: "integer"),
        new OA\Property(property: "time_zone_id", type: "string"),
        new OA\Property(property: "time_zone_label", type: "string"),
        new OA\Property(property: "invite_only_registration", type: "boolean"),
        new OA\Property(property: "meeting_room_booking_start_time", type: "integer", description: "Unix timestamp"),
        new OA\Property(property: "meeting_room_booking_end_time", type: "integer", description: "Unix timestamp"),
        new OA\Property(property: "meeting_room_booking_slot_length", type: "integer"),
        new OA\Property(property: "meeting_room_booking_max_allowed", type: "integer"),
        new OA\Property(property: "begin_allow_booking_date", type: "integer", description: "Unix timestamp"),
        new OA\Property(property: "end_allow_booking_date", type: "integer", description: "Unix timestamp"),
        new OA\Property(property: "logo", type: "string", format: "url"),
        new OA\Property(property: "secondary_logo", type: "string", format: "url"),
        new OA\Property(property: "reassign_ticket_till_date", type: "integer", description: "Unix timestamp"),
        new OA\Property(property: "registration_disclaimer_content", type: "string"),
        new OA\Property(property: "registration_disclaimer_mandatory", type: "boolean"),
        new OA\Property(property: "registration_reminder_email_days_interval", type: "integer"),
        new OA\Property(property: "registration_link", type: "string", format: "url"),
        new OA\Property(property: "secondary_registration_link", type: "string", format: "url"),
        new OA\Property(property: "secondary_registration_label", type: "string"),
        new OA\Property(property: "registration_send_qr_as_image_attachment_on_ticket_email", type: "boolean"),
        new OA\Property(property: "registration_send_ticket_as_pdf_attachment_on_ticket_email", type: "boolean"),
        new OA\Property(property: "registration_send_ticket_email_automatically", type: "boolean"),
        new OA\Property(property: "registration_send_order_email_automatically", type: "boolean"),
        new OA\Property(property: "registration_allow_automatic_reminder_emails", type: "boolean"),
        new OA\Property(property: "registration_allowed_refund_request_till_date", type: "integer", description: "Unix timestamp"),
        new OA\Property(property: "registration_slug_prefix", type: "string"),
        new OA\Property(property: "modality", type: "string"),
        new OA\Property(property: "allow_update_attendee_extra_questions", type: "boolean"),
        new OA\Property(property: "default_page_url", type: "string"),
        new OA\Property(property: "speaker_confirmation_default_page_url", type: "string"),
        new OA\Property(property: "virtual_site_url", type: "string"),
        new OA\Property(property: "marketing_site_url", type: "string"),
        new OA\Property(property: "marketing_site_oauth2_client_scopes", type: "string"),
        new OA\Property(property: "support_email", type: "string", format: "email"),
        new OA\Property(property: "speakers_support_email", type: "string", format: "email"),
        new OA\Property(property: "default_ticket_type_currency", type: "string"),
        new OA\Property(property: "default_ticket_type_currency_symbol", type: "string"),
        new OA\Property(
            property: "supported_currencies",
            type: "array",
            items: new OA\Items(type: "string"),
            description: "Array of currency codes"
        ),
    ]
)]
class SummitSchema {}
