<?php

namespace App\Swagger\schemas;

use OpenApi\Attributes as OA;


#[OA\Schema(
    schema: 'Summit',
    type: 'object',
    properties: [
        new OA\Property(property: 'id', type: 'integer', example: 1),
        new OA\Property(property: 'created', type: 'integer', example: 1, format: 'ime_epoch'),
        new OA\Property(property: 'last_edited', type: 'integer', example: 1, format: 'ime_epoch'),

        new OA\Property(property: 'name', type: 'string' ),
        new OA\Property(property: 'start_date', type: 'integer', format: 'ime_epoch' ),
        new OA\Property(property: 'end_date', type: 'integer', format: 'ime_epoch' ),
        new OA\Property(property: 'registration_begin_date', type: 'integer', format: 'ime_epoch' ),
        new OA\Property(property: 'registration_end_date', type: 'integer', format: 'ime_epoch' ),
        new OA\Property(property: 'start_showing_venues_date', type: 'integer', format: 'ime_epoch' ),
        new OA\Property(property: 'schedule_start_date', type: 'integer', format: 'ime_epoch' ),
        new OA\Property(property: 'active', type: 'boolean' ),
        new OA\Property(property: 'type_id', type: 'integer' ),
        new OA\Property(property: 'dates_label', type: 'string' ),
        new OA\Property(property: 'max_submission_allowed_per_user', type: 'integer' ),
        new OA\Property(property: 'published_events_count', type: 'integer' ),
        new OA\Property(property: 'time_zone_id', type: 'string' ),
        new OA\Property(property: 'slug', type: 'string' ),
        new OA\Property(property: 'invite_only_registration', type: 'boolean' ),
        new OA\Property(property: 'meeting_room_booking_start_time', type: 'integer', format: 'ime_epoch' ),
        new OA\Property(property: 'meeting_room_booking_end_time', type: 'integer', format: 'ime_epoch' ),
        new OA\Property(property: 'meeting_room_booking_slot_length', type: 'integer' ),
        new OA\Property(property: 'meeting_room_booking_max_allowed', type: 'integer' ),
        new OA\Property(property: 'begin_allow_booking_date', type: 'integer', format: 'ime_epoch' ),
        new OA\Property(property: 'end_allow_booking_date', type: 'integer', format: 'ime_epoch' ),
        new OA\Property(property: 'logo', type: 'url' ),
        new OA\Property(property: 'secondary_logo', type: 'url' ),
        new OA\Property(property: 'reassign_ticket_till_date', type: 'integer', format: 'ime_epoch' ),
        new OA\Property(property: 'registration_disclaimer_content', type: 'string' ),
        new OA\Property(property: 'registration_disclaimer_mandatory', type: 'boolean' ),
        new OA\Property(property: 'registration_reminder_email_days_interval', type: 'integer' ),
        new OA\Property(property: 'registration_link', type: 'url' ),
        new OA\Property(property: 'secondary_registration_link', type: 'url' ),
        new OA\Property(property: 'secondary_registration_label', type: 'string' ),
        new OA\Property(property: 'schedule_default_page_url', type: 'url' ),
        new OA\Property(property: 'schedule_default_event_detail_url', type: 'url' ),
        new OA\Property(property: 'schedule_og_site_name', type: 'string' ),
        new OA\Property(property: 'schedule_og_image_url', type: 'string' ),
        new OA\Property(property: 'schedule_og_image_secure_url', type: 'string' ),
        new OA\Property(property: 'schedule_og_image_width', type: 'integer' ),
        new OA\Property(property: 'schedule_og_image_height', type: 'integer' ),
        new OA\Property(property: 'schedule_facebook_app_id', type: 'string' ),
        new OA\Property(property: 'schedule_ios_app_name', type: 'string' ),
        new OA\Property(property: 'schedule_ios_app_store_id', type: 'string' ),
        new OA\Property(property: 'schedule_ios_app_custom_schema', type: 'string' ),
        new OA\Property(property: 'schedule_android_app_name', type: 'string' ),
        new OA\Property(property: 'schedule_android_app_package', type: 'string' ),
        new OA\Property(property: 'schedule_android_custom_schema', type: 'string' ),
        new OA\Property(property: 'schedule_twitter_app_name', type: 'string' ),
        new OA\Property(property: 'schedule_twitter_text', type: 'string' ),
        new OA\Property(property: 'default_page_url', type: 'string' ),
        new OA\Property(property: 'speaker_confirmation_default_page_url', type: 'string' ),
        new OA\Property(property: 'virtual_site_url', type: 'string' ),
        new OA\Property(property: 'marketing_site_url', type: 'string' ),
        new OA\Property(property: 'support_email', type: 'string' ),
        new OA\Property(property: 'speakers_support_email', type: 'string' ),
        new OA\Property(property: 'registration_send_qr_as_image_attachment_on_ticket_email', type: 'boolean' ),
        new OA\Property(property: 'registration_send_ticket_as_pdf_attachment_on_ticket_email', type: 'boolean' ),
        new OA\Property(property: 'registration_send_ticket_email_automatically', type: 'boolean' ),
        new OA\Property(property: 'registration_send_order_email_automatically', type: 'boolean' ),
        new OA\Property(property: 'registration_allow_automatic_reminder_emails', type: 'boolean' ),
        new OA\Property(property: 'modality', type: 'string' ),
        new OA\Property(property: 'allow_update_attendee_extra_questions', type: 'boolean' ),
        new OA\Property(property: 'time_zone_label', type: 'string' ),
        new OA\Property(property: 'registration_allowed_refund_request_till_date', type: 'integer', format: 'ime_epoch' ),
        new OA\Property(property: 'registration_slug_prefix', type: 'string' ),
        new OA\Property(property: 'marketing_site_oauth2_client_scopes', type: 'string' ),
        new OA\Property(property: 'default_ticket_type_currency', type: 'string' ),
        new OA\Property(property: 'default_ticket_type_currency_symbol', type: 'string' ),
        new OA\Property(property: 'ticket_types', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")) ),
        new OA\Property(property: 'locations', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=locations, full objects when included in expand.' ),
        new OA\Property(property: 'wifi_connections', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=wifi_connections, full objects when included in expand.' ),
        new OA\Property(property: 'selection_plans', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=selection_plans, full objects when included in expand.' ),
        new OA\Property(property: 'meeting_booking_room_allowed_attributes', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=meeting_booking_room_allowed_attributes, full objects when included in expand.' ),
        new OA\Property(property: 'summit_sponsors', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=summit_sponsors, full objects when included in expand.' ),
        new OA\Property(property: 'order_extra_questions', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=order_extra_questions, full objects when included in expand.' ),
        new OA\Property(property: 'tax_types', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=tax_types, full objects when included in expand.' ),
        new OA\Property(property: 'payment_profiles', type: 'array', items: new OA\Items(new OA\Schema(type: "object")), description: 'Array of PaymentGatewayProfile, when included in ?relations=payment_profiles, full objects when included in expand.' ),
        new OA\Property(property: 'email_flows_events', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=email_flows_events, full objects when included in expand.' ),
        new OA\Property(property: 'summit_documents', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=summit_documents, full objects when included in expand.' ),
        new OA\Property(property: 'featured_speakers', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=featured_speakers, full objects when included in expand.' ),
        new OA\Property(property: 'dates_with_events', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=dates_with_events, full objects when included in expand.' ),
        new OA\Property(property: 'presentation_action_types', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=presentation_action_types, full objects when included in expand.' ),
        new OA\Property(property: 'schedule_settings', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=schedule_settings, full objects when included in expand.' ),
        new OA\Property(property: 'badge_view_types', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=badge_view_types, full objects when included in expand.' ),
        new OA\Property(property: 'lead_report_settings', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=lead_report_settings, full objects when included in expand.' ),
        new OA\Property(property: 'badge_types', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=badge_types, full objects when included in expand.' ),
        new OA\Property(property: 'badge_features_types', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=badge_features_types, full objects when included in expand.' ),
        new OA\Property(property: 'badge_access_level_types', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=badge_access_level_types, full objects when included in expand.' ),
        new OA\Property(property: 'dates_with_events', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=dates_with_events, full objects when included in expand.' ),
        new OA\Property(property: 'supported_currencies', type: 'array', items: new OA\Items(new OA\Schema(type: "integer")), description: 'Array of Ids, when included in ?relations=supported_currencies, full objects when included in expand.' ),

    ])
]
class SummitSchema
{
}
